workflows:
  - name: checks
    remove_jobs:
      # This will be resolved in:
      #   https://github.com/exasol/udf-mock-python/issues/86
      - check-format
      # This will be resolved in:
      #   https://github.com/exasol/udf-mock-python/issues/88
      - lint-typing
      # This is needed because this project does not need `matrix-all.yml` or `matrix-exasol.yml`.
      # This job will be re-activated in:
      #   https://github.com/exasol/udf-mock-python/issues/89
      - check-workflows
  - name: merge-gate
    remove_jobs:
      # There are not yet slow checks for this project.
      - approve-run-slow-tests
      - run-slow-checks
  - name: periodic-validation
    remove_jobs:
      # There are not yet slow checks for this project.
      - run-slow-checks
