from pathlib import Path

from exasol.toolbox.config import BaseConfig

ROOT_DIR = Path(__file__).parent

from pydantic import computed_field


class Config(BaseConfig):
    @computed_field  # type: ignore[misc]
    @property
    def source_code_path(self) -> Path:
        """
        Path to the source code of the project.

        In transformers-extension, this needs to be overridden due to a custom directory
        setup. This will be addressed in:
            https://github.com/exasol/udf-mock-python/issues/80
        """
        return self.root_path / self.project_name

    @computed_field  # type: ignore[misc]
    @property
    def version_filepath(self) -> Path:
        """
        Path to the ``version.py`` file included in the project. This is an
        autogenerated file which contains the version of the code. It is maintained by
        the nox sessions ``version:check`` and ``release:prepare``.

         In transformers-extension, this needs to be overridden due to a custom directory
        setup & custom `version.py` location. This will be addressed in:
            https://github.com/exasol/udf-mock-python/issues/79
        """
        return self.root_path / "version.py"


PROJECT_CONFIG = Config(
    project_name="exasol-udf-mock-python",
    root_path=ROOT_DIR,
    python_versions=("3.10", "3.11", "3.12", "3.13"),
)
